services:
  db:
    image: postgres:16-alpine
    container_name: noc_db
    environment:
      POSTGRES_DB: dashboard_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
